name: state_managment_sample
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  ## Provider
  provider: 6.0.5

  ## Bloc
  bloc: ^8.1.0

  ## RXDart
  rxdart: 0.27.7

  ## Riverpod
  flutter_riverpod: ^2.3.6

  ## Mobx / MobxFlutter
  mobx: 2.2.0
  flutter_mobx: 2.0.6+5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  bloc_test: ^9.1.0
  mobx_codegen: 2.3.0

flutter:
  uses-material-design: true